services:
  mongodb:
    image: mongo:latest
    container_name: fravega_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: fravega
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: